apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amicable-preview-router
  namespace: amicable
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-intern-dns
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "*.amicable-preview.data.mayflower.zone"
      secretName: amicable-preview-wildcard-tls
  rules:
    - host: "*.amicable-preview.data.mayflower.zone"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: amicable-preview-router
                port:
                  number: 80
