apiVersion: v1
kind: Service
metadata:
  name: amicable-preview-router
  namespace: amicable
spec:
  selector:
    app: amicable-preview-router
  ports:
    - name: http
      port: 80
      targetPort: 80
